Repository kritikaparmar-programmer/HealthCheck, pull requests merged in 2021-03, with the labels that each got.

#22 Resolved Issue #15 Heart Disease Prediction
  Models/heart_model
  Notebooks/HeartNotebook.ipynb
Labels: GSSOC21, bug, enhancement, level2

#39 Liver disease
  Datasets/indian_liver_patient.csv
  Models/liver-disease_model.pkl
  Notebooks/Liver_Disease_Prediction.ipynb
Labels: level3

#31 added welcome bot
  .github/config.yml
Labels: GSSOC21, level1

#69 Added Stroke Prevention Model
  Datasets/stroke_data.csv
  Models/model.pkl
  Notebooks/Stroke.ipynb
Labels: GSSOC21, level3

#30 Resolving issue #19 : Added Pneumonia Detection Notebook
  Notebooks/PneumoniaDetection.ipynb
Labels: GSSOC21, level3

#78 Parkinson
  Datasets/parkinsons.data
  Models/parkinson_model.pkl
  Notebooks/CancerPrediction.ipynb
  Notebooks/ParkinsonPrediction.ipynb
Labels: GSSOC21, level3

#84 Added Contributor !!
  README.md
Labels: GSSOC21, level0

#52 Issue no.- #49 Added enhancement to DiabetesNotebook.ipynb
  Models/diabetes-model.pkl
  Notebooks/DiabetesNotebook.ipynb
  Notebooks/FetalHealthClassification_Imbalanced.ipynb
  Notebooks/HeartNotebook.ipynb
Labels: GSSOC21, level3

#123 [Gssoc'21] Fix the Internal Server Error and Navbar toggle which was not working.
  static/favicon.ico
  static/style.css
  templates/c_result.html
  templates/cancer.html
  templates/d_result.html
  templates/diabetes.html
  templates/fetal_health.html
  templates/h_result.html
  templates/heart.html
  templates/index.html
  templates/layout.html
Labels: GSSOC21

#87 Fixed: Updated Readme.md Issue #9
  README.md
Labels: GSSOC21, level0

#129 Heart-attack model is tuned
  Models/Heart_Attack_DNN.pb
  Notebooks/Heart-Attack_Notebook.ipynb
Labels: Changes Requested, GSSOC21, level3

#141 Created using Colaboratory
  Notebooks/OralCancer.ipynb
Labels: GSSOC21, level3
