Repository kritikaparmar-programmer/HealthCheck, pull requests merged in 2021-04, with the labels that each got.

#138 [Gssoc'21] Added the Dark mode and toggle button.
  static/css/darkmode.css
  static/js/darkmode.js
  static/style.css
  templates/fetal_health.html
  templates/layout.html
Labels: GSSOC21, level2

#86 Add files via upload
  Notebooks/Heart_disease_prediction.ipynb
Labels: Changes Requested, GSSOC21, level2

#137 Adding Time series forecasting covid 19 case notebook #115
  Notebooks/Time series forecasting covid 19 case.ipynb
Labels: GSSOC21, level3

#158 resolve Issue 62
  static/style.css
  templates/d_result.html
  templates/diabetes.html
  templates/h_result.html
  templates/heart.html
Labels: GSSOC21, level2

#168 Diabetes model improved (Resolved Issue #157)
  Models/diabetes_model_improved.pkl
  Notebooks/Diabetes_prediction_with proper_analysis.ipynb
Labels: GSSOC21, Machine Learning, level3

#125 Added Pancreatic Cancer Prediction Notebook
  Models/Pancreatic_Cancer_model.pkl
  Notebooks/Pancreatic Cancer Predictions.ipynb
  Notebooks/ParkinsonPrediction.ipynb
  Notebooks/PneumoniaDetection.ipynb
Labels: Changes Requested

#193 Fixed Diabetes Notebook with latest changes as per 14/4/2021
  Notebooks/DiabetesNotebook_fixed.ipynb
  Notebooks/RFmodel.pkl
Labels: GSSOC21, Machine Learning, level2

#99 Chronic Kidney Disease Analysis
  Datasets/kidney_disease.csv
  Notebooks/Chronic_Kidney_Disease.ipynb
Labels: Changes Requested, GSSOC21, level2

#201 Added the no.of forks,issues,pr's,stars and license and repo size. Al…
  README.md
Labels: GSSOC21, level1
